Added Supermicro vendor theme
AdisonCavani/distro-grub-themes pull request #118
Opened 2023-10-13 03:16 UTC by Jackson5551

# Description

Added Supermicro vendor theme for use on Supermicro server and workstation boards.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project (correct file and folder structure)
- [x] The background image for theme follows naming convention: `theme_name.png`
- [x] I updated [`themes.json`](https://github.com/AdisonCavani/distro-grub-themes/blob/master/themes.json) file (JSON database)

2023-10-13 03:26 UTC, Jackson5551 commented
I have the .psd file as well and will provide that upon request.

2023-10-13 11:53 UTC, AdisonCavani requested changes

2023-10-13 11:53 UTC, AdisonCavani commented on themes.json
Move this to the end of the file:
```json
{
      "name": "Supermicro",
      "versionAdded": "v3.3"
}
```

2023-10-13 12:28 UTC, Jackson5551 commented on themes.json
Done

2023-10-14 09:36 UTC, AdisonCavani approved these changes

2023-10-14 09:37 UTC, merged

2023-10-14 09:38 UTC, AdisonCavani commented
You can provide the `psd` file here

2023-10-14 16:55 UTC, Jackson5551 commented
[supermicro_1080p.zip](https://github.com/AdisonCavani/distro-grub-themes/files/12906929/supermicro_1080p.zip)