Adding HP Omen theme
AdisonCavani/distro-grub-themes pull request #133
Opened 2024-05-04 19:54 UTC by jaherron

# Description

I added an image in the backgrounds folder for HP Omen, and ran the Actions workflow. An entry for this theme was also added in the themes.json file, but I don't know where it should have gone so I put it below the one for generic HP.

I wanted to make this contribution since I recently got an Omen laptop and I like using these themes for when I install distros that don't come with a GRUB theme.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project (correct file and folder structure)
- [x] The background image for theme follows naming convention: `theme_name.png`
- [x] I updated [`themes.json`](https://github.com/AdisonCavani/distro-grub-themes/blob/master/themes.json) file (JSON database)

2024-05-04 19:58 UTC, AdisonCavani requested changes

2024-05-04 19:58 UTC, AdisonCavani commented on themes.json
> +      "name": "HP Omen"
Move it to the bottom of `themes.json` and add versionAdded

```json
{
      "name": "HP Omen",
      "versionAdded": "v3.3"
}
```

2024-05-04 22:12 UTC, jaherron commented on themes.json
> +      "versionAdded": "v3.3"
I moved the lines in the file and added the version number as requested.

2024-05-05 11:01 UTC, AdisonCavani approved these changes

2024-05-18 11:00 UTC, merged